version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: dev.dockerfile
    container_name: opensuite-api
    ports:
      - "${API_PORT}:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=${DB_SERVER},${DB_PORT};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD} TrustServerCertificate=True;
